apiVersion: v1
kind: Service
metadata:
  name: tracking-service
spec:
  selector:
    app: tracking
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30036
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tracking
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tracking
  template:
    metadata:
      labels:
        app: tracking
    spec:
      containers:
        - name: tracking
          image: tracking-generator:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "default"